# Install extension Rest client in vs code to test post requests

# POST http://127.0.0.1:5000/split HTTP/1.1
# content-type: application/json

# {
#     "product_id": 5,
#     "quantities": ["20","30"]
# }

# POST http://127.0.0.1:5000/register HTTP/1.1
# content-type: application/json

# {
#     "username": "fate",
#     "password": "2703",
#     "fullname": "fatema",
#     "role": "farmer"
# }

# POST http://127.0.0.1:5000/merge HTTP/1.1
# content-type: application/json

# {
#     "childrenIds": [6,7],
#     "ownerId": "137f8dd76837941037a63f22cc277577bf41c94d3be55c232ee6e9fea8cb465e"
# }

# GET http://127.0.0.1:5000/getuser HTTP/1.1