# Install extension Rest client in vs code to test post requests

# POST http://127.0.0.1:5000/split HTTP/1.1
# content-type: application/json

# {
#     "product_id": 5,
#     "quantities": ["20","30"]
# }

# POST http://127.0.0.1:5000/register HTTP/1.1
# content-type: application/json

# {
#     "username": "anay",
#     "password": "2703",
#     "fullname": "anay",
#     "role": "transporter"
# }

# id1 502d33c9ff5648efa78d0636bd40ff38b7e46bf6b156369a7e464b27e1fa4584
# id2 7c156f0f28d0569a46c425fe4545ad462bdeb23426946dcd9f96cdbc1d73ea14


# POST http://127.0.0.1:5000/transfer HTTP/1.1
# content-type: application/json

# {
#     "senderId": "502d33c9ff5648efa78d0636bd40ff38b7e46bf6b156369a7e464b27e1fa4584",
#     "receiverId": "7c156f0f28d0569a46c425fe4545ad462bdeb23426946dcd9f96cdbc1d73ea14",
#     "productId": "1",
#     "location": "Mumbai"
# }

# POST http://127.0.0.1:5000/merge HTTP/1.1
# content-type: application/json

# {
#     "childrenIds": [6,7],
#     "ownerId": "137f8dd76837941037a63f22cc277577bf41c94d3be55c232ee6e9fea8cb465e"
# }

# GET http://127.0.0.1:5000/getuser HTTP/1.1

# POST http://127.0.0.1:5000/login HTTP/2
# content-type: application/json

# {
#     "username": "anay",
#     "password": "2703"
# }

# GET http://127.0.0.1:5000/protected HTTP/2
# Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MDY0NTMxNTIsIm5iZiI6MTYwNjQ1MzE1MiwianRpIjoiMzYzMWQ4NmMtODJjOS00ZjdjLWI1OGUtZjVkZGIwY2VmZjdkIiwiZXhwIjoxNjA2NDU0MDUyLCJpZGVudGl0eSI6ImFuYXkiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.8ojwjoHei3J5A8rEax4iB7dVQ3JZhnjMMYpYVgV0xsM

###

POST http://127.0.0.1:5000/parents HTTP/1.1
content-type: application/json

{
    "user_id":1,
    "parents":[
        {"product_id":1,"quantity":30},
        {"product_id":2,"quantity":50}
    ]
}


###
POST http://127.0.0.1:5000/add_product HTTP/1.1
content-type: application/json

{
    "product_name":"andda",
    "product_properties":{"quantity":50},
    "user_id":"user_id"
}

###
GET http://127.0.0.1:5000/get_products/1 HTTP/1.1