# Install extension Rest client in VSCode to test HTTP requests

# Testing the /split [POST] endpoint
POST http://127.0.0.1:5000/split HTTP/1.1
content-type: application/json

{
    "product_id": 1,
    "quantities": ["20","30"],
    "user_id":"c6ff365f60a9e375b982bae164bb67065814c75a5e478ac82aa7267696d7943e"
}


###
# Testing the /register [POST] endpoint
POST http://127.0.0.1:5000/register HTTP/1.1
content-type: application/json

{
    "username": "JaneSmith22",
    "password": "janey",
    "fullname": "Jane Smith",
    "role": "Transporter"
}


###
# Testing the /transfer [POST] endpoint
# id1 e0c2ee138764f6a304c8bfd6ee046ad3be1353aaee0e91a6baf63ad1c464a0da
# id2 f038ba9c0704d9592982863a3f42f4e65fddb98de431555e9af55d099d779425
POST http://127.0.0.1:5000/transfer HTTP/2
content-type: application/json

{
    "senderId": "84e8c99ed1593f69837a5c811b1a29148feee1251d4345e28f01017a8e8037a1",
    "receiverId": "4e7fd341b5813a112c19f88a866bf2bbbee72f5d44ba94f17a754b302454f7aa",
    "productId": "1",
    "props":"good Condition",
    "location": "Mumbai"
}


###
# Testing the /merge [POST] endpoint
POST http://127.0.0.1:5000/merge HTTP/1.1
content-type: application/json

{
    "childrenIds": [6,7],
    "ownerId": "137f8dd76837941037a63f22cc277577bf41c94d3be55c232ee6e9fea8cb465e"
}


###
# # Testing the /getuser [GET] endpoint
# GET http://127.0.0.1:5000/getuser HTTP/1.1


###
# Testing the /login [POST] endpoint
POST http://127.0.0.1:5000/login HTTP/2
content-type: application/json

{
    "username": "john_doe",
    "password": "1234"
}


###
# Testing the /protected [GET] endpoint with
# the JWT token in the Authorization header
GET http://127.0.0.1:5000/protected HTTP/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MDY0NTMxNTIsIm5iZiI6MTYwNjQ1MzE1MiwianRpIjoiMzYzMWQ4NmMtODJjOS00ZjdjLWI1OGUtZjVkZGIwY2VmZjdkIiwiZXhwIjoxNjA2NDU0MDUyLCJpZGVudGl0eSI6ImFuYXkiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.8ojwjoHei3J5A8rEax4iB7dVQ3JZhnjMMYpYVgV0xsM


###
# Testing the /parents [POST] endpoint
POST http://127.0.0.1:5000/parents HTTP/1.1
content-type: application/json

{
    "user_id":1,
    "parents":[
        {"product_id":1,"quantity":30},
        {"product_id":2,"quantity":50}
    ]
}


###
# Testing the /add_product [POST] endpoint
POST http://127.0.0.1:5000/add_product HTTP/1.1
content-type: application/json

{
    "product_name":"Sugarcane",
    "product_properties":{"quantity":1000},
    "user_id": "84e8c99ed1593f69837a5c811b1a29148feee1251d4345e28f01017a8e8037a1"
}


###
# Testing the /get_products [GET] endpoint
GET http://127.0.0.1:5000/get_products/c6ff365f60a9e375b982bae164bb67065814c75a5e478ac82aa7267696d7943e HTTP/1.1
###
GET http://127.0.0.1:5000/get_products/user_id HTTP/1.1
###
POST http://127.0.0.1:5000/trace HTTP/2
content-type: application/json

{
    "product_id": "1",
    "user_id": "c6ff365f60a9e375b982bae164bb67065814c75a5e478ac82aa7267696d7943e"
}
