# Install extension Rest client in VSCode to test HTTP requests

# Testing the /split [POST] endpoint
POST http://127.0.0.1:5000/split HTTP/1.1
content-type: application/json

{
    "product_id": 59,
    "quantities": ["1200","800"],
    "user_id":"10d98c494dede35e8b542c44eb9b01efe935934166ddef63e18313410d39b484"
}


###
# Testing the /register [POST] endpoint
POST http://127.0.0.1:5000/register HTTP/1.1
content-type: application/json

{
    "username": "al",
    "password": "pw",
    "fullname": "fatema",
    "role": "Distributor"
}


###
# Testing the /transfer [POST] endpoint
POST http://127.0.0.1:5000/transfer HTTP/2
content-type: application/json

{
    "senderId": "c63c7f7fef43745b2b3f0f96c6e4703012959c145843ccf9d3bdadc6364306a0",
    "receiverId": "30c952fab122c3f9759f02a6d95c3758b246b4fee239957b2d4fee46e26170c4",
    "productId": "7",
    "props":"good Condition",
    "location": "Mumbai"
}


###
# Testing the /merge [POST] endpoint
POST http://127.0.0.1:5000/merge HTTP/1.1
content-type: application/json

{
    "childrenIds": [6,7],
    "ownerId": "ad1b8786c138c0fbb3a68a3456b168f21cc81c6e16515db80172d500f6b6941a"
}


###
# # Testing the /getuser [GET] endpoint
# GET http://127.0.0.1:5000/getuser HTTP/1.1


###
# Testing the /login [POST] endpoint
POST http://127.0.0.1:5000/login HTTP/2
content-type: application/json

{
    "username": "al",
    "password": "pw"
}


###
# Testing the /protected [GET] endpoint with
# the JWT token in the Authorization header
GET http://127.0.0.1:5000/protected HTTP/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MDY0NTMxNTIsIm5iZiI6MTYwNjQ1MzE1MiwianRpIjoiMzYzMWQ4NmMtODJjOS00ZjdjLWI1OGUtZjVkZGIwY2VmZjdkIiwiZXhwIjoxNjA2NDU0MDUyLCJpZGVudGl0eSI6ImFuYXkiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.8ojwjoHei3J5A8rEax4iB7dVQ3JZhnjMMYpYVgV0xsM


###
# Testing the /parents [POST] endpoint
POST http://127.0.0.1:5000/parents HTTP/1.1
content-type: application/json

{
    "user_id":1,
    "parents":[
        {"product_id":1,"quantity":30},
        {"product_id":2,"quantity":50}
    ]
}


###
# Testing the /add_product [POST] endpoint
POST http://127.0.0.1:5000/add_product HTTP/1.1
content-type: application/json

{
    "product_name":"Prod 1",
    "product_properties":{"quantity":2000},
    "user_id": "c63c7f7fef43745b2b3f0f96c6e4703012959c145843ccf9d3bdadc6364306a0",
    "parent_ids": [-1]
}


###
# Testing the /get_products [GET] endpoint
GET http://127.0.0.1:5000/get_products/c63c7f7fef43745b2b3f0f96c6e4703012959c145843ccf9d3bdadc6364306a0 HTTP/1.1
###

GET http://127.0.0.1:5000/get_products/7d9071962a52f85673ec2654d4dd24f667d5e6f21591fa480b0ddc2920d98eb7 HTTP/1.1
###
# GET http://127.0.0.1:5000/get_products HTTP/1.1
# content-type: application/json

# {
#     "user_id": "ad1b8786c138c0fbb3a68a3456b168f21cc81c6e16515db80172d500f6b6941a"
# }
###
POST http://127.0.0.1:5000/trace HTTP/2
content-type: application/json

{
    "product_id": "2",
    "user_id": "c63c7f7fef43745b2b3f0f96c6e4703012959c145843ccf9d3bdadc6364306a0"
}
