# Install extension Rest client in VSCode to test HTTP requests

# Testing the /split [POST] endpoint
POST http://127.0.0.1:5000/split HTTP/1.1
content-type: application/json

{
    "product_id": 7,
    "quantities": ["300","700"],
    "user_id":"5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"
}


###
# Testing the /register [POST] endpoint
POST http://127.0.0.1:5000/register HTTP/1.1
content-type: application/json

{
    "username": "alpha",
    "password": "password",
    "fullname": "anayk",
    "role": "Retailer"
}


###
# Testing the /transfer [POST] endpoint
POST http://127.0.0.1:5000/transfer HTTP/2
content-type: application/json

{
    "senderId": "84e8c99ed1593f69837a5c811b1a29148feee1251d4345e28f01017a8e8037a1",
    "receiverId": "4e7fd341b5813a112c19f88a866bf2bbbee72f5d44ba94f17a754b302454f7aa",
    "productId": "1",
    "props":"good Condition",
    "location": "Mumbai"
}


###
# Testing the /merge [POST] endpoint
POST http://127.0.0.1:5000/merge HTTP/1.1
content-type: application/json

{
    "childrenIds": [6,7],
    "ownerId": "137f8dd76837941037a63f22cc277577bf41c94d3be55c232ee6e9fea8cb465e"
}


###
# # Testing the /getuser [GET] endpoint
# GET http://127.0.0.1:5000/getuser HTTP/1.1


###
# Testing the /login [POST] endpoint
POST http://127.0.0.1:5000/login HTTP/2
content-type: application/json

{
    "username": "alpha",
    "password": "password"
}


###
# Testing the /protected [GET] endpoint with
# the JWT token in the Authorization header
GET http://127.0.0.1:5000/protected HTTP/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MDY0NTMxNTIsIm5iZiI6MTYwNjQ1MzE1MiwianRpIjoiMzYzMWQ4NmMtODJjOS00ZjdjLWI1OGUtZjVkZGIwY2VmZjdkIiwiZXhwIjoxNjA2NDU0MDUyLCJpZGVudGl0eSI6ImFuYXkiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.8ojwjoHei3J5A8rEax4iB7dVQ3JZhnjMMYpYVgV0xsM


###
# Testing the /parents [POST] endpoint
POST http://127.0.0.1:5000/parents HTTP/1.1
content-type: application/json

{
    "user_id":1,`
    "parents":[
        {"product_id":1,"quantity":30},
        {"product_id":2,"quantity":50}
    ]
}


###
# Testing the /add_product [POST] endpoint
POST http://127.0.0.1:5000/add_product HTTP/1.1
content-type: application/json

{
    "product_name":"Sugarcane",
    "product_properties":{"quantity":1000},
    "user_id": "ad1b8786c138c0fbb3a68a3456b168f21cc81c6e16515db80172d500f6b6941a"
}


###
# Testing the /get_products [GET] endpoint
GET http://127.0.0.1:5000/get_products/5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8 HTTP/1.1
###
GET http://127.0.0.1:5000/get_products HTTP/1.1
content-type: application/json

{
    "user_id": "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"
}
###
POST http://127.0.0.1:5000/trace HTTP/2
content-type: application/json

{
    "product_id": "5",
    "user_id": "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"
}
